"""add duplicate_reviews table

Revision ID: 3ff89d9e3ea3
Revises: 68b20e6f2add
Create Date: 2026-09-20 12:13:31.419625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff89d9e3ea3'
down_revision: Union[str, Sequence[str], None] = '68b20e6f2add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_reviews',
    sa.Column('review_id', sa.String(length=32), nullable=False),
    sa.Column('record_id_1', sa.String(length=32), nullable=False),
    sa.Column('record_id_2', sa.String(length=32), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_duplicate_reviews_record_id_1'), 'duplicate_reviews', ['record_id_1'], unique=False)
    op.create_index(op.f('ix_duplicate_reviews_record_id_2'), 'duplicate_reviews', ['record_id_2'], unique=False)
    op.create_index(op.f('ix_duplicate_reviews_review_id'), 'duplicate_reviews', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duplicate_reviews_review_id'), table_name='duplicate_reviews')
    op.drop_index(op.f('ix_duplicate_reviews_record_id_2'), table_name='duplicate_reviews')
    op.drop_index(op.f('ix_duplicate_reviews_record_id_1'), table_name='duplicate_reviews')
    op.drop_table('duplicate_reviews')
    # ### end Alembic commands ###
