"""initial schema

Revision ID: 68b20e6f2add
Revises: 
Create Date: 2026-09-20 12:02:12.733494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b20e6f2add'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('ration_card_id', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('taluka', sa.String(length=64), nullable=False),
    sa.Column('village', sa.String(length=64), nullable=False),
    sa.Column('annual_income', sa.Integer(), nullable=False),
    sa.Column('social_category', sa.String(length=32), nullable=False),
    sa.Column('housing_status', sa.String(length=32), nullable=False),
    sa.Column('land_holding_acres', sa.Float(), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_index(op.f('ix_families_district'), 'families', ['district'], unique=False)
    op.create_index(op.f('ix_families_family_id'), 'families', ['family_id'], unique=False)
    op.create_index(op.f('ix_families_ration_card_id'), 'families', ['ration_card_id'], unique=False)
    op.create_table('officers',
    sa.Column('officer_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('officer_id')
    )
    op.create_index(op.f('ix_officers_district'), 'officers', ['district'], unique=False)
    op.create_index(op.f('ix_officers_officer_id'), 'officers', ['officer_id'], unique=False)
    op.create_table('schemes',
    sa.Column('scheme_id', sa.String(length=32), nullable=False),
    sa.Column('scheme_name', sa.String(length=256), nullable=False),
    sa.Column('department', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=False),
    sa.Column('application_url', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_id'), 'schemes', ['scheme_id'], unique=False)
    op.create_table('eligibility_rules',
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('scheme_id', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_eligibility_rules_rule_id'), 'eligibility_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_eligibility_rules_scheme_id'), 'eligibility_rules', ['scheme_id'], unique=False)
    op.create_table('family_members',
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('relation_to_head', sa.String(length=32), nullable=False),
    sa.Column('education_level', sa.String(length=64), nullable=True),
    sa.Column('student_status', sa.Boolean(), nullable=False),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('disability_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_member_id'), 'family_members', ['member_id'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('scheme_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_officer', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.member_id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_applications_family_id'), 'applications', ['family_id'], unique=False)
    op.create_index(op.f('ix_applications_member_id'), 'applications', ['member_id'], unique=False)
    op.create_index(op.f('ix_applications_scheme_id'), 'applications', ['scheme_id'], unique=False)
    op.create_table('benefits',
    sa.Column('benefit_id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('scheme_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.member_id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ),
    sa.PrimaryKeyConstraint('benefit_id')
    )
    op.create_index(op.f('ix_benefits_benefit_id'), 'benefits', ['benefit_id'], unique=False)
    op.create_index(op.f('ix_benefits_family_id'), 'benefits', ['family_id'], unique=False)
    op.create_index(op.f('ix_benefits_member_id'), 'benefits', ['member_id'], unique=False)
    op.create_index(op.f('ix_benefits_scheme_id'), 'benefits', ['scheme_id'], unique=False)
    op.create_table('identity_records',
    sa.Column('record_id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_member_id', sa.String(length=64), nullable=False),
    sa.Column('name_as_recorded', sa.String(length=128), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('village', sa.String(length=64), nullable=False),
    sa.Column('ration_card_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.member_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_identity_records_district'), 'identity_records', ['district'], unique=False)
    op.create_index(op.f('ix_identity_records_member_id'), 'identity_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_identity_records_record_id'), 'identity_records', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_records_record_id'), table_name='identity_records')
    op.drop_index(op.f('ix_identity_records_member_id'), table_name='identity_records')
    op.drop_index(op.f('ix_identity_records_district'), table_name='identity_records')
    op.drop_table('identity_records')
    op.drop_index(op.f('ix_benefits_scheme_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_member_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_family_id'), table_name='benefits')
    op.drop_index(op.f('ix_benefits_benefit_id'), table_name='benefits')
    op.drop_table('benefits')
    op.drop_index(op.f('ix_applications_scheme_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_member_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_family_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_family_members_member_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_eligibility_rules_scheme_id'), table_name='eligibility_rules')
    op.drop_index(op.f('ix_eligibility_rules_rule_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_schemes_scheme_id'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_officers_officer_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_district'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_families_ration_card_id'), table_name='families')
    op.drop_index(op.f('ix_families_family_id'), table_name='families')
    op.drop_index(op.f('ix_families_district'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
